from decouple import config

DEBUG = config('DEBUG', default=True, cast= bool)
SECRET_KEY = config('SECRET_KEY')
ALGORITHM = config('ALGORITHM')
DATABASE_URL = config('DATABASE_URL')
ACCESS_TOKEN_EXPIRES_MINUTES = config('ACCESS_TOKEN_EXPIRES_MINUTES')
DATABASE_LOGIN_USERNAME = config('DATABASE_LOGIN_USERNAME')
DATABASE_LOGIN_PASSWORD = config('DATABASE_LOGIN_PASSWORD')

